<a href="https://colab.research.google.com/github/Harshit2502/100-days-of-deep-learning/blob/main/pytorch_breastcancel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import random
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['Unnamed: 32', 'id'], inplace=True)
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

# Train Test Split

In [5]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

# Scaling

In [6]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [7]:
X_train

array([[ 0.37102646,  0.11855399,  0.41266273, ...,  1.44605458,
         0.44562385,  0.98687579],
       [ 0.32882255, -1.16954069,  0.41673633, ...,  1.85136619,
         2.8085573 ,  0.85356823],
       [-0.51525561,  0.62612195, -0.50593581, ..., -0.49348067,
        -1.02163011,  0.38152835],
       ...,
       [-0.52650999, -0.09575248, -0.58618588, ..., -1.1209686 ,
        -0.56500918, -0.64286376],
       [ 0.36258568,  0.00801697,  0.38414747, ...,  0.54155404,
        -0.11317799, -0.19923368],
       [ 0.06997192, -0.65520516,  0.07659009, ...,  0.39254242,
         0.23168257,  0.20779145]])

In [8]:
y_train

392    M
22     M
163    B
138    M
469    B
      ..
540    B
372    M
334    B
131    M
340    B
Name: diagnosis, Length: 455, dtype: object

# Label encoding

In [9]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [10]:
y_train

array([1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0,

# Numpy to pytorch tensors

In [11]:
X_train_tensor = torch.from_numpy(X_train).float()
X_test_tensor = torch.from_numpy(X_test).float()
y_train_tensor = torch.from_numpy(y_train).float()
y_test_tensor = torch.from_numpy(y_test).float()

In [12]:
X_train_tensor.shape
y_train_tensor.shape

torch.Size([455])

In [13]:
from torch.utils.data import DataLoader,Dataset
import torch.nn as nn


class Custom_Dataset(Dataset):

  def __init__(self,features,labels):

    self.features = features
    self.labels = labels

  def __len__(self):
    return len(self.features)

  def __getitem__(self,idx):
    return self.features[idx],self.labels[idx]



In [14]:
train_dataset = Custom_Dataset(X_train_tensor,y_train_tensor)
test_dataset = Custom_Dataset(X_test_tensor,y_test_tensor)

In [15]:
train_dataset[10]

(tensor([ 1.2039,  0.5562,  1.1378,  1.1730, -0.1795, -0.1480,  0.3321,  0.4754,
         -0.4428, -0.7850,  0.6318, -0.0372,  0.4011,  0.5512, -0.3743, -0.6264,
         -0.0887, -0.4391, -0.6838, -0.6381,  1.2633,  0.8858,  1.1112,  1.2123,
          0.5850, -0.1662,  0.6076,  0.3404,  0.3211, -0.4227]),
 tensor(1.))

In [16]:
train_loader = DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader = DataLoader(test_dataset,batch_size=32,shuffle=True)

# Defining the neural model

In [17]:
import torch.nn as nn

class MysimpleNN(nn.Module):
  def __init__(self,input_size):
    super(MysimpleNN,self).__init__()
    self.linear = nn.Linear(input_size,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,x):
    out = self.linear(x)
    out = self.sigmoid(out)

    return out

# Important Parameters

In [18]:
learning_rate = 0.1
epochs = 25


In [19]:
loss_function = nn.BCELoss()

# Traing pipeline

In [20]:
#creating a model
model = MysimpleNN(X_train_tensor.shape[1])

#define optimizer
optimizer = torch.optim.SGD(model.parameters(),lr=learning_rate)

#define loop
for epoch in range(epochs):

  for batch_features,batch_labels in train_loader:

    #forward pass
    y_pred = model(X_train_tensor)
    #loss calculate
    loss = loss_function(y_pred,y_train_tensor.view(-1,1))

    optimizer.zero_grad()

    #backward pass
    loss.backward()

    #parameter update
    optimizer.step()



    #print loss in each epoch
    print(f'Epoch:{epoch+1},loss:{loss.item()}')

Epoch:1,loss:0.5856896638870239
Epoch:1,loss:0.47037744522094727
Epoch:1,loss:0.40395501255989075
Epoch:1,loss:0.36049187183380127
Epoch:1,loss:0.32943010330200195
Epoch:1,loss:0.30585977435112
Epoch:1,loss:0.2871938943862915
Epoch:1,loss:0.271934449672699
Epoch:1,loss:0.2591499388217926
Epoch:1,loss:0.24822869896888733
Epoch:1,loss:0.23875105381011963
Epoch:1,loss:0.2304185926914215
Epoch:1,loss:0.22301283478736877
Epoch:1,loss:0.21636974811553955
Epoch:1,loss:0.2103634476661682
Epoch:2,loss:0.20489557087421417
Epoch:2,loss:0.19988802075386047
Epoch:2,loss:0.1952778548002243
Epoch:2,loss:0.19101367890834808
Epoch:2,loss:0.1870531290769577
Epoch:2,loss:0.18336084485054016
Epoch:2,loss:0.17990706861019135
Epoch:2,loss:0.17666654288768768
Epoch:2,loss:0.17361775040626526
Epoch:2,loss:0.17074202001094818
Epoch:2,loss:0.16802330315113068
Epoch:2,loss:0.16544747352600098
Epoch:2,loss:0.16300229728221893
Epoch:2,loss:0.16067691147327423
Epoch:2,loss:0.15846168994903564
Epoch:3,loss:0.1563481

In [21]:
model.linear.bias

Parameter containing:
tensor([-0.4176], requires_grad=True)

In [22]:
model.eval()
accuracy_list = []

with torch.no_grad():
  for batch_features,batch_labels in test_loader:
    y_pred = model(batch_features)
    y_pred = (y_pred > 0.8).float()
    batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
    accuracy_list.append(batch_accuracy)

overall_accuracy =  sum(accuracy_list)/len(accuracy_list)
print(f'Accuracy:{overall_accuracy:.4f}')

Accuracy:0.9470


In [23]:
print(y_pred)

tensor([[0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])
